apiVersion: v1
kind: Secret
type: cos-csi-s3-driver
metadata:
  name: csi-cos-s3-pvc-v3
data:
  # echo -n "https://s3.ap-geo.objectstorage.softlayer.net" | base64
  cos-endpoint: aHR0cHM6Ly9zMy5hcC1nZW8ub2JqZWN0c3RvcmFnZS5zb2Z0bGF5ZXIubmV0
  # echo -n "ap-standard" | base64
  regn-class: YXAtc3RhbmRhcmQ= 
  # echo -n "nkapdevtest" | base64
  bucket-name: bmthcGRldnRlc3Q=
  access-key: TFRibXNkUWdvdFRLWFI5cG5ZWW4=
  secret-key: ZzRUMTc5M05yaks5WnYzc1hubmUwOFhWTzIyQURwSmJORTZKVVNyOQ==

